// flow-typed signature: ce0bfb2d0ebbe812a81b4d71e0a56fee
// flow-typed version: <<STUB>>/js-theme_v0.6.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-theme/lib/index' {
  declare module.exports: any;
}

declare module 'js-theme/lib/mergeProps' {
  declare module.exports: any;
}

declare module 'js-theme/lib/Theme' {
  declare module.exports: any;
}

declare module 'js-theme/lib/Theme.story' {
  declare module.exports: any;
}

declare module 'js-theme/lib/Theme.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-theme/lib/index.js' {
  declare module.exports: $Exports<'js-theme/lib/index'>;
}
declare module 'js-theme/lib/mergeProps.js' {
  declare module.exports: $Exports<'js-theme/lib/mergeProps'>;
}
declare module 'js-theme/lib/Theme.js' {
  declare module.exports: $Exports<'js-theme/lib/Theme'>;
}
declare module 'js-theme/lib/Theme.story.js' {
  declare module.exports: $Exports<'js-theme/lib/Theme.story'>;
}
declare module 'js-theme/lib/Theme.test.js' {
  declare module.exports: $Exports<'js-theme/lib/Theme.test'>;
}
