// flow-typed signature: 64ce1032809a1ae733f85155881e8d73
// flow-typed version: <<STUB>>/rc-animate_v^2.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-animate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-animate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-animate/lib/Animate' {
  declare module.exports: any;
}

declare module 'rc-animate/lib/AnimateChild' {
  declare module.exports: any;
}

declare module 'rc-animate/lib/ChildrenUtils' {
  declare module.exports: any;
}

declare module 'rc-animate/lib/index' {
  declare module.exports: any;
}

declare module 'rc-animate/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-animate/lib/Animate.js' {
  declare module.exports: $Exports<'rc-animate/lib/Animate'>;
}
declare module 'rc-animate/lib/AnimateChild.js' {
  declare module.exports: $Exports<'rc-animate/lib/AnimateChild'>;
}
declare module 'rc-animate/lib/ChildrenUtils.js' {
  declare module.exports: $Exports<'rc-animate/lib/ChildrenUtils'>;
}
declare module 'rc-animate/lib/index.js' {
  declare module.exports: $Exports<'rc-animate/lib/index'>;
}
declare module 'rc-animate/lib/util.js' {
  declare module.exports: $Exports<'rc-animate/lib/util'>;
}
