// flow-typed signature: b988f7009cf5134082665a071e716391
// flow-typed version: <<STUB>>/rc-util_v^4.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-util/lib/Children/mapSelf' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Children/toArray' {
  declare module.exports: any;
}

declare module 'rc-util/lib/createChainedFunction' {
  declare module.exports: any;
}

declare module 'rc-util/lib/deprecated' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/addEventListener' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/canUseDom' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/class' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/contains' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/css' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/focus' {
  declare module.exports: any;
}

declare module 'rc-util/lib/Dom/support' {
  declare module.exports: any;
}

declare module 'rc-util/lib/getContainerRenderMixin' {
  declare module.exports: any;
}

declare module 'rc-util/lib/getScrollBarSize' {
  declare module.exports: any;
}

declare module 'rc-util/lib/guid' {
  declare module.exports: any;
}

declare module 'rc-util/lib/KeyCode' {
  declare module.exports: any;
}

declare module 'rc-util/lib/pickAttrs' {
  declare module.exports: any;
}

declare module 'rc-util/lib/warn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-util/lib/Children/mapSelf.js' {
  declare module.exports: $Exports<'rc-util/lib/Children/mapSelf'>;
}
declare module 'rc-util/lib/Children/toArray.js' {
  declare module.exports: $Exports<'rc-util/lib/Children/toArray'>;
}
declare module 'rc-util/lib/createChainedFunction.js' {
  declare module.exports: $Exports<'rc-util/lib/createChainedFunction'>;
}
declare module 'rc-util/lib/deprecated.js' {
  declare module.exports: $Exports<'rc-util/lib/deprecated'>;
}
declare module 'rc-util/lib/Dom/addEventListener.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/addEventListener'>;
}
declare module 'rc-util/lib/Dom/canUseDom.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/canUseDom'>;
}
declare module 'rc-util/lib/Dom/class.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/class'>;
}
declare module 'rc-util/lib/Dom/contains.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/contains'>;
}
declare module 'rc-util/lib/Dom/css.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/css'>;
}
declare module 'rc-util/lib/Dom/focus.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/focus'>;
}
declare module 'rc-util/lib/Dom/support.js' {
  declare module.exports: $Exports<'rc-util/lib/Dom/support'>;
}
declare module 'rc-util/lib/getContainerRenderMixin.js' {
  declare module.exports: $Exports<'rc-util/lib/getContainerRenderMixin'>;
}
declare module 'rc-util/lib/getScrollBarSize.js' {
  declare module.exports: $Exports<'rc-util/lib/getScrollBarSize'>;
}
declare module 'rc-util/lib/guid.js' {
  declare module.exports: $Exports<'rc-util/lib/guid'>;
}
declare module 'rc-util/lib/KeyCode.js' {
  declare module.exports: $Exports<'rc-util/lib/KeyCode'>;
}
declare module 'rc-util/lib/pickAttrs.js' {
  declare module.exports: $Exports<'rc-util/lib/pickAttrs'>;
}
declare module 'rc-util/lib/warn.js' {
  declare module.exports: $Exports<'rc-util/lib/warn'>;
}
