// flow-typed signature: 011a76aef04b175e3f43061921eca393
// flow-typed version: <<STUB>>/webpack-svgstore-plugin_v^2.2.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-svgstore-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-svgstore-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-svgstore-plugin/helpers/svgxhr' {
  declare module.exports: any;
}

declare module 'webpack-svgstore-plugin/helpers/utils' {
  declare module.exports: any;
}

declare module 'webpack-svgstore-plugin/platform/global' {
  declare module.exports: any;
}

declare module 'webpack-svgstore-plugin/platform/static/js/index' {
  declare module.exports: any;
}

declare module 'webpack-svgstore-plugin/platform/static/test' {
  declare module.exports: any;
}

declare module 'webpack-svgstore-plugin/test/index' {
  declare module.exports: any;
}

declare module 'webpack-svgstore-plugin/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-svgstore-plugin/helpers/svgxhr.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/helpers/svgxhr'>;
}
declare module 'webpack-svgstore-plugin/helpers/utils.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/helpers/utils'>;
}
declare module 'webpack-svgstore-plugin/index' {
  declare module.exports: $Exports<'webpack-svgstore-plugin'>;
}
declare module 'webpack-svgstore-plugin/index.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin'>;
}
declare module 'webpack-svgstore-plugin/platform/global.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/platform/global'>;
}
declare module 'webpack-svgstore-plugin/platform/static/js/index.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/platform/static/js/index'>;
}
declare module 'webpack-svgstore-plugin/platform/static/test.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/platform/static/test'>;
}
declare module 'webpack-svgstore-plugin/test/index.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/test/index'>;
}
declare module 'webpack-svgstore-plugin/webpack.config.js' {
  declare module.exports: $Exports<'webpack-svgstore-plugin/webpack.config'>;
}
